[en]
  title = "Streaming Video Party Tool"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"
  [en.params]
    logoText = "Streaming Video Party Tool"
  
[zh-tw]
  title = "同步視聽小工具"
  languageName = "繁體中文"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/zh-tw"
  [zh-tw.params]
    logoText = "同步視聽小工具"

